### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by bermarte**
Refactor and documentation

### CODE REVIEW

**Comment by tahminarasoli** [comment]
@bermarte I wish we could work together on these parts.

**Comment by bermarte** [comment]
Sorry Tahmina, it was something extra. I wasn't sure you wanted to go further with it. There is a small problem I am fixing at the moment. Are you interested to help?

**Comment by tahminarasoli** [comment]
it was a chance to learn from you because still, I don't know how to do this part. yes, I would be happy if you share.

**Comment by bermarte** [comment]
The problem is that the TDs don't have a maxlength property (it should be 60 characters max if you check the input fields provided).

**Comment by bermarte** [comment]
@tahminarasoli You find it in a branch called **convertText**.

**Comment by bermarte** [comment]
@tahminarasoli 
- You could also add more unit-tests. You find the script to modify in `src/tests/todoTest.js` and execute it in the browser opening the file `./public/test.html`

**Comment by tahminarasoli** [comment]
I don't want to interrupt you, I will try it locally you can continue with your work. all the best!

**Comment by bermarte** [comment]
For me, it's not a problem if you want to help me or if you want to work a bit on it. If you want, we can talk via zoom in half an hour. It's up to you.

**Comment by tahminarasoli** [comment]
> 
> 
> For me, it's not a problem if you want to help me or if you want to work a bit on it. If you want, we can talk via zoom in half an hour. It's up to you.
> This is the new class https://github.com/bermarte/encapsulation-list-prototype/blob/convertText/src/classes/Todo.js

yeah, I was following you brought a lot of changes in the project. now it looks like a well-organized project.

**Comment by bermarte** [comment]
@tahminarasoli Another thing to do could be the refactoring of the Validator class, and to create an object from it. It would be interesting.

**Comment by bermarte** [comment]
@tahmina if you see what is changed in the Todo class you could modify `loadTodos.js` and `saveLocal.js`, at the moment they don't work.

**Pull request merged**
